version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: redsocial
      MYSQL_USER: administrador
      MYSQL_PASSWORD: administrador_pass
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
